apiVersion: v1
kind: Pod
metadata:
  name: eapp-pod
  labels:
    app: eapp
    env: dev
spec:
  containers:
    - name: eapp-container
      image: nginx:latest
      ports:
        - containerPort: 80
      env:
        - name: name
          value: anupam
        - name: age
          value: "28"

---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  password: <Password>
