apiVersion: v1
kind: Pod
metadata:
  name: tst-pod
  labels:
    app: test
    env: dev
spec:
  restartPolicy: Always
  containers:
    - name: tst-container
      image: anupam
      args: ["echo", "hello anupam"]
