apiVersion: v1
kind: Service
metadata:
  name: oneapp-ui-service
  labels:
    app: oneapp-ui
    tier: frontend
    project: oneanupam
spec:
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
  selector:
    app: oneapp-ui
    tier: frontend
