apiVersion: v1
kind: Pod
metadata:
  name: curl-pod
  labels:
    name: curl
    env: bld
spec:
  containers:
    - name: curl-container
      image: curlimages/curl:latest
      command: ["sleep", "3600"]
      imagePullPolicy: IfNotPresent
  restartPolicy: Never
